// Native audio services for Chatter (AVFoundation, Accelerate, Speech).
import Foundation
import Testing

/// Test fixtures generated by Tools/make_fixtures.py from Chatter's Python worker.
enum Fixtures {
    static func url(_ name: String) throws -> URL {
        try #require(Bundle.module.url(forResource: name, withExtension: nil, subdirectory: "Fixtures"),
                     "Missing fixture \(name)")
    }

    static func data(_ name: String) throws -> Data { try Data(contentsOf: url(name)) }

    /// Raw little-endian float32 samples.
    static func floats(_ name: String) throws -> [Float] {
        let bytes = try data(name)
        return bytes.withUnsafeBytes { raw in
            (0..<(bytes.count / 4)).map { Float(bitPattern: UInt32(littleEndian: raw.loadUnaligned(fromByteOffset: $0 * 4, as: UInt32.self))) }
        }
    }

    static func json<T: Decodable>(_ name: String, as type: T.Type) throws -> T {
        try JSONDecoder().decode(T.self, from: data(name))
    }
}

/// Deterministic signals mirroring `tone`/`noise`/`zeros` in Tools/make_fixtures.py.
enum TestSignals {
    static let rate = 44100.0

    static func count(_ seconds: Double) -> Int { Int((seconds * rate).rounded(.toNearestOrEven)) }

    static func tone(_ seconds: Double, amplitude: Double, frequency: Double) -> [Float] {
        (0..<count(seconds)).map { Float(amplitude * sin(2 * Double.pi * frequency * Double($0) / rate)) }
    }

    /// 64-bit LCG noise in [−1, 1) scaled in float32, identical to the Python generator.
    static func noise(_ seconds: Double, amplitude: Double, seed: UInt64) -> [Float] {
        var state = seed
        let scale = Float(amplitude)
        return (0..<count(seconds)).map { _ in
            state = state &* 6364136223846793005 &+ 1442695040888963407
            return Float(Double(state >> 40) / 16777216.0 * 2 - 1) * scale
        }
    }

    static func zeros(_ seconds: Double) -> [Float] { [Float](repeating: 0, count: count(seconds)) }

    static func add(_ a: [Float], _ b: [Float]) -> [Float] { zip(a, b).map { $0 + $1 } }

    /// The named signals of `health_expected.json`.
    static func healthCase(_ name: String) -> [Float] {
        switch name {
        case "silence": return zeros(12)
        case "quiet": return tone(15, amplitude: 0.01, frequency: 220)
        case "clipping": return tone(20, amplitude: 1.2, frequency: 220).map { min(1, max(-1, $0)) }
        case "long":
            var signal: [Float] = []
            var elapsed = 0.0
            while elapsed < 40.5 - 1e-9 {
                signal += tone(1.0, amplitude: 0.2, frequency: 220) + zeros(0.5)
                elapsed += 1.5
            }
            return signal
        case "short": return noise(5, amplitude: 0.3, seed: 7)
        case "ideal": return add(tone(22, amplitude: 0.1, frequency: 220), noise(22, amplitude: 0.01, seed: 11))
        case "tiny": return tone(300 / rate, amplitude: 0.5, frequency: 220)
        default: return []
        }
    }
}

/// A uniquely named scratch directory, removed by `remove()`.
struct ScratchDirectory {
    let url: URL

    init() throws {
        url = FileManager.default.temporaryDirectory
            .appendingPathComponent("ChatterAudioKitTests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
    }

    func file(_ name: String) -> URL { url.appendingPathComponent(name) }

    func contents() throws -> [String] {
        try FileManager.default.contentsOfDirectory(atPath: url.path(percentEncoded: false)).sorted()
    }

    func remove() { try? FileManager.default.removeItem(at: url) }
}

/// Builds minimal WAV files (PCM or IEEE float) for decoder edge cases.
enum WAVBuilder {
    static func float32(_ interleaved: [Float], channels: Int, sampleRate: Int) -> Data {
        var payload = Data()
        for sample in interleaved { withUnsafeBytes(of: sample.bitPattern.littleEndian) { payload.append(contentsOf: $0) } }
        return wav(format: 3, bits: 32, channels: channels, sampleRate: sampleRate, payload: payload)
    }

    static func silentPCM16(frames: Int, sampleRate: Int) -> Data {
        wav(format: 1, bits: 16, channels: 1, sampleRate: sampleRate, payload: Data(count: frames * 2))
    }

    static func wav(format: UInt16, bits: UInt16, channels: Int, sampleRate: Int, payload: Data) -> Data {
        var data = Data()
        func u32(_ value: UInt32) { withUnsafeBytes(of: value.littleEndian) { data.append(contentsOf: $0) } }
        func u16(_ value: UInt16) { withUnsafeBytes(of: value.littleEndian) { data.append(contentsOf: $0) } }
        let blockAlign = UInt16(channels) * bits / 8
        data.append(contentsOf: Array("RIFF".utf8)); u32(UInt32(36 + payload.count)); data.append(contentsOf: Array("WAVE".utf8))
        data.append(contentsOf: Array("fmt ".utf8)); u32(16); u16(format); u16(UInt16(channels)); u32(UInt32(sampleRate))
        u32(UInt32(sampleRate) * UInt32(blockAlign)); u16(blockAlign); u16(bits)
        data.append(contentsOf: Array("data".utf8)); u32(UInt32(payload.count))
        data.append(payload)
        return data
    }
}

/// Signal measurements used by several suites.
enum Measure {
    static func rms(_ samples: some Collection<Float>) -> Double {
        guard !samples.isEmpty else { return 0 }
        return (samples.reduce(0.0) { $0 + Double($1) * Double($1) } / Double(samples.count)).squareRoot()
    }

    /// Signal-to-noise ratio of `actual` against `expected`, in dB.
    static func snr(expected: [Float], actual: [Float]) -> Double {
        var signal = 0.0, noise = 0.0
        for (e, a) in zip(expected, actual) {
            signal += Double(e) * Double(e)
            noise += (Double(a) - Double(e)) * (Double(a) - Double(e))
        }
        return 10 * log10(signal / noise)
    }

    /// Sign changes per sample.
    static func zeroCrossingRate(_ samples: ArraySlice<Float>) -> Double {
        var crossings = 0
        var previous = samples.first ?? 0
        for sample in samples.dropFirst() {
            if (previous < 0) != (sample < 0) { crossings += 1 }
            previous = sample
        }
        return Double(crossings) / Double(max(1, samples.count - 1))
    }
}
